name: pyuvdata
channels:
  - conda-forge
dependencies:
  - astropy>=6.0
  - astropy-healpix>=1.0.2
  - astroquery>=0.4.4
  - coverage
  - cython>=3.0
  - docstring_parser>=0.15
  - h5py>=3.4
  - hdf5plugin>=3.2.0
  - matplotlib
  - numpy>=1.23
  - pip
  - pre-commit
  - pyerfa>=2.0.1.1
  - pypandoc
  - pytest>=8.2.0
  - pytest-cases>=3.8.3
  - pytest-cov
  - pytest-xdist
  - python-casacore>=3.5.2
  - pyyaml>=5.4.1
  - scipy>=1.8
  - setuptools_scm>=8.1
  - sphinx
  - pip:
      - lunarsky>=0.2.5
      - novas
      - novas_de405
