name: External Tests
on: [push, pull_request]

jobs:
  hera_cal:
    name: hera_cal
    env:
      ENV_NAME: hera_cal_tests
      PYTHON: 3.9
    runs-on: ubuntu-latest
    defaults:
     run:
       # Adding -l {0} helps ensure conda can be found properly in windows.
       shell: bash -l {0}
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: clone hera_cal
        run: |
          cd ../
          git clone https://github.com/HERA-Team/hera_cal.git
          cp hera_cal/ci/${{ env.ENV_NAME }}.yml pyuvdata/ci/
          cd pyuvdata

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ format('{0}-conda-{1}-{2}',
              runner.os,
              env.CACHE_NUMBER,
              hashFiles(format('./ci/{0}.yml', env.ENV_NAME))) }}

      - name: Setup Minimamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          python-version: ${{ env.PYTHON }}
          environment-file: ./ci/${{ env.ENV_NAME }}.yml
          activate-environment: ${{ env.ENV_NAME }}

      - name: Conda Info
        run: |
          conda info -a
          conda list
          PYVER=`python -c "import sys; print('{:d}.{:d}'.format(sys.version_info.major, sys.version_info.minor))"`
          if [[ $PYVER != $PYTHON ]]; then
            exit 1;
          fi

      - name: Install pyuvdata
        run: |
          pip install --no-deps .

      - name: Install hera_cal
        run: |
          cd ../
          cd hera_cal
          pip install --no-deps .

      - name: run hera_cal tests
        run: |
          cd ../
          cd hera_cal
          mkdir test-reports
          python -m pytest hera_cal --junitxml=test-reports/xunit.xml

  hera_qm:
    name: hera_qm
    env:
      ENV_NAME: hera_qm_tests
      PYTHON: 3.9
    runs-on: ubuntu-latest
    defaults:
     run:
       # Adding -l {0} helps ensure conda can be found properly in windows.
       shell: bash -l {0}
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: clone hera_qm
        run: |
          cd ../
          git clone https://github.com/HERA-Team/hera_qm.git
          cp hera_qm/ci/${{ env.ENV_NAME }}.yml pyuvdata/ci/
          cd pyuvdata

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ format('{0}-conda-{1}-{2}',
              runner.os,
              env.CACHE_NUMBER,
              hashFiles(format('./ci/{0}.yml', env.ENV_NAME))) }}

      - name: Setup Minimamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          python-version: ${{ env.PYTHON }}
          environment-file: ./ci/${{ env.ENV_NAME }}.yml
          activate-environment: ${{ env.ENV_NAME }}

      - name: Conda Info
        run: |
          conda info -a
          conda list
          PYVER=`python -c "import sys; print('{:d}.{:d}'.format(sys.version_info.major, sys.version_info.minor))"`
          if [[ $PYVER != $PYTHON ]]; then
            exit 1;
          fi

      - name: Install pyuvdata
        run: |
          pip install --no-deps .

      - name: Install hera_qm
        run: |
          cd ../
          cd hera_qm
          pip install --no-deps .

      - name: run hera_qm tests
        run: |
          cd ../
          cd hera_qm
          mkdir test-reports
          python -m pytest hera_qm --junitxml=test-reports/xunit.xml
